<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="L-00008" name="Test" tests="1" failures="0" timestamp="19 Oct 2016 16:51:10 GMT" time="3.673" errors="0">
  <testcase name="@BeforeTest setUp" time="0.0" classname="TestSuite.TestMakeOrder">
    <failure type="org.openqa.selenium.SessionNotCreatedException" message="session not created exception
from unknown error: Runtime.executionContextCreated has invalid &amp;apos;context&amp;apos;: {&amp;quot;auxData&amp;quot;:{&amp;quot;frameId&amp;quot;:&amp;quot;1488.1&amp;quot;,&amp;quot;isDefault&amp;quot;:true},&amp;quot;id&amp;quot;:1,&amp;quot;name&amp;quot;:&amp;quot;&amp;quot;,&amp;quot;origin&amp;quot;:&amp;quot;://&amp;quot;}
  (Session info: chrome=54.0.2840.59)
  (Driver info: chromedriver=2.23.409699 (49b0fa931cda1caad0ae15b7d1b68004acd05129),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 2.52 seconds
Build info: version: &amp;apos;unknown&amp;apos;, revision: &amp;apos;31c43c8&amp;apos;, time: &amp;apos;2016-08-02 21:57:56 -0700&amp;apos;
System info: host: &amp;apos;L-00008&amp;apos;, ip: &amp;apos;10.64.228.76&amp;apos;, os.name: &amp;apos;Windows 7&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;6.1&amp;apos;, java.version: &amp;apos;1.8.0_91&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"1488.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=54.0.2840.59)
  (Driver info: chromedriver=2.23.409699 (49b0fa931cda1caad0ae15b7d1b68004acd05129),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 2.52 seconds
Build info: version: 'unknown', revision: '31c43c8', time: '2016-08-02 21:57:56 -0700'
System info: host: 'L-00008', ip: '10.64.228.76', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.chrome.ChromeDriver
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:683)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:247)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:143)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:170)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:159)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:148)
	at PageObjects.BrowserLoader.initBrowser(BrowserLoader.java:106)
	at PageObjects.BrowserLoader.<init>(BrowserLoader.java:32)
	at TestSuite.TestMakeOrder.setUp(TestMakeOrder.java:48)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeTest setUp -->
  <testcase name="@AfterClass tearDown" time="0.0" classname="TestSuite.TestMakeOrder">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at TestSuite.TestMakeOrder.tearDown(TestMakeOrder.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- @AfterClass tearDown -->
  <testcase name="testSignInWithCorrectInfo" time="0.001" classname="TestSuite.TestMakeOrder">
    <skipped/>
  </testcase> <!-- testSignInWithCorrectInfo -->
</testsuite> <!-- Test -->
