<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite thread-count="2" verbose="0" name="Failed suite [CheckoutSuite]" parallel="tests">
  <test name="Test(failed)" parallel="classes">
    <classes>
      <class name="TestSuite.CheckoutSuite.FW1242">
        <methods>
          <include name="setUp"/>
          <include name="tearDown"/>
        </methods>
      </class> <!-- TestSuite.CheckoutSuite.FW1242 -->
      <class name="TestSuite.CheckoutSuite.FW1238">
        <methods>
          <include name="setUp"/>
          <include name="tearDown"/>
        </methods>
      </class> <!-- TestSuite.CheckoutSuite.FW1238 -->
      <class name="TestSuite.CheckoutSuite.FW1230">
        <methods>
          <include name="testAddNewCCForOrder"/>
          <include name="tearDown"/>
          <include name="setUp"/>
        </methods>
      </class> <!-- TestSuite.CheckoutSuite.FW1230 -->
      <class name="TestSuite.CheckoutSuite.FW1212">
        <methods>
          <include name="tearDown"/>
          <include name="setUp"/>
          <include name="anonymousCheckOut"/>
        </methods>
      </class> <!-- TestSuite.CheckoutSuite.FW1212 -->
    </classes>
  </test> <!-- Test(failed) -->
</suite> <!-- Failed suite [CheckoutSuite] -->
